### ISSUE TITLE
Allow the use of local .env files instead of being built into the docker image

### ISSUE THREAD

**Issue by albertsyh** [Airstrip-AI/airstrip#2]
Right now the `sample.env` file is injected directly into the docker image and doesn't allow env variables to be injected during runtime. This happens on both the FE and BE.

**Comment by hendychua** [comment]
Changes made in https://github.com/hendychua/airstrip/commit/54626354c686a2dca5e12990154fc4c2a164aeb8. Note that for `airstrip-fe`, which uses NextJS and bakes the env vars into the build, the variables have to be changed in Dockerfile.
